secretName: "zenith-ssh-key-secret"
appName: "zenith-client"

zenithClient:
  image:
    repository: ghcr.io/stackhpc/zenith-client
    tag: 0.10.1
  resources: {}

podHostNetwork: false

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
