apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
stringData:
  ssh_key: |
    {{- .Values.zenithClient.sshKey.private | nindent 4 }}
  ssh_key.pub: |
    {{- .Values.zenithClient.sshKey.public | nindent 4 }}
  client.yaml: |
    {{- tpl (toYaml .Values.zenithClient.config) . | nindent 4 }}
